// kalkulator.manifest.ts
// Generated by Factory (P2B-equivalent) — documents final state of section

export const SECTION_MANIFEST = {
  slug: 'kalkulator',
  type: 'A',
  requires: ['gsap', '@gsap/react'],

  assets: [],

  warmup: [],

  scrollTriggersCount: 0,

  geometryMutable: false,
  geometryRefresh: 'none',

  dciProps: [],

  timelineContract: undefined,

  specialNotes: {
    breakpoints: [1500, 1200, 800, 500, 400, 315, 290],
    platformGuards: [],
    cpuGatingMechanism: 'N/A',
    cpuGatingPath: undefined,
  },

  integrationNotes: {
    hasPin: false,
    hasSnap: false,
    affectsGeometryBelow: false,
    sensitiveTo: [],
    testWith: [],
    overflowXNote: 'Flip animation sets document.documentElement.style.overflowX = hidden for 2.5s during 3D flip. Guard: cleanup on unmount + onComplete reset. Option B accepted — no architectural change needed.',
  },

  perf: {
    dynamicImport: false,
    isHero: false,
    gracefulDegradation: true,
    preloadCandidates: [],
    prefetchCandidates: [],
    coldCandidates: [],
    preconnectDomains: [],
    containApplied: false,
    warnings: [],
  },

  scrollRuntimeRecommendations: [],

  runtimeChecks: {
    'CLN-01': 'PENDING',
    'SM-01': 'PENDING',
    'SM-02': 'PENDING',
    'INT-01': 'N/A',
    'INT-02': 'N/A',
    'INT-03': 'N/A',
  },

  evidence: {
    pipelineComplete: true,
    auditComplete: true,
    factoryHardeningComplete: true,
    cpuGatingImplemented: false,
    criticalBlockers: 0,

    ioGatingAssessment: 'NOT REQUIRED — Type A, no continuous per-frame loop, counter rAF is event-driven + self-terminating, OPT-6 visibilitychange pauses rAF in background tabs',

    geometryContract: {
      type: 'normal',
      syntheticContextAllowed: true,
      entryExitInvariant: false,
      preserveExistingGuards: true,
    },

    safariTarget: '13.1+',
    safariCompat: {
      insetLonghand: true,
      flexGapMarginFallback: true,
      rotateInTransform: true,
    },

    gsapVersion: {
      sandbox: '3.12.5 (CDN)',
      production: '3.12.7 (npm)',
    },

    qaSynthesis: {
      fixesApplied: 7,
      optimizationsApplied: 4,
      blockerDecisions: {
        B1: 'OPTION B — Safari 13.1+ full compat (inset + gap + rotate)',
      },
    },

    workflowAudit: {
      'RED-01': 'FIXED — import gsap from gsap (Factory)',
      'RED-02': 'FIXED — useGSAP for engine, 7 useEffect verified as non-GSAP',
      'RED-03': 'FIXED — Font injection removed (Factory)',
      'RED-04': 'ACCEPTED (Option B) — overflowX guards sufficient',
      'RED-05': 'FIXED — module-level state removed with CDN loader (Factory)',
      'RED-06': 'FIXED — this manifest',
      'YLW-01': 'FIXED — CSS extracted to kalkulator-section.css (Factory)',
      'YLW-02': 'ACCEPTED — imperative engine behind ref fence',
      'YLW-03': 'ACCEPTED — correct SSR guard pattern',
      'YLW-04': 'ACCEPTED — cleanup in destroy()',
      'YLW-05': 'ACCEPTED — cleanup in useEffect return',
      'YLW-06': 'FIXED — use client added',
      'YLW-07': 'FIXED — dotKeyframes in CSS file (Factory)',
    },
  },
};
